<a href="https://colab.research.google.com/github/jelly-decoder28/poppy-june/blob/main/NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy handles array manipulation, random numbers, and statistics

3D arrays: tensor (matrices 1,2,3,4)

In [4]:
import numpy as np #import library to use function
v = np.array([1, 2, 3, 4, 5])
print("1D Array", v)
print(f"Shape:{v.shape}")

1D Array [1 2 3 4 5]
Shape:(5,)


In [5]:
A = np.array ([[1,2,3], [4,5,6],[7,8,9]])
print("2D Array")
print(A)
print(f"Shape:{A.shape}")

2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:(3, 3)


In [8]:
T = np.array([[[1,2], [3,4]],
             [[5,6],[7,8]],
             [[9,10],[11,12]]]) #dimensions --> stacks
print("3D array (Tensor): ")
print(T)
print(f"Shape: {T.shape}")

3D array (Tensor): 
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape: (3, 2, 2)
